### ISSUE TITLE
bug: TesseractError: Estimating resolution as X

### ISSUE THREAD

**Issue by qued** [Unstructured-IO/unstructured#2900]
**Describe the bug**
User gets a `TesseractError` when processing a document.

**To Reproduce**
Code was an API call with a certain image-based document.

**Expected behavior**
Document processed successfully.

**Environment Info**
Running in self-hosted open-source API.
Unstructured version 0.12.3.
Tesseract version 5.3.3

**Additional context**
User was able to successfully process the document with Tesseract version 4.1.1

Stack trace:
```python
File "/home/notebook-user/unstructured/partition/pdf.py", line 213, in partition_pdf
    return partition_pdf_or_image(
  File "/home/notebook-user/unstructured/partition/pdf.py", line 298, in partition_pdf_or_image
    elements = _partition_pdf_or_image_local(
  File "/home/notebook-user/unstructured/utils.py", line 214, in wrapper
    return func(*args, **kwargs)
  File "/home/notebook-user/unstructured/partition/pdf.py", line 494, in _partition_pdf_or_image_local
    final_document_layout = process_data_with_ocr(
  File "/home/notebook-user/unstructured/partition/pdf_image/ocr.py", line 82, in process_data_with_ocr
    merged_layouts = process_file_with_ocr(
  File "/home/notebook-user/unstructured/utils.py", line 214, in wrapper
    return func(*args, **kwargs)
  File "/home/notebook-user/unstructured/partition/pdf_image/ocr.py", line 178, in process_file_with_ocr
    raise e
  File "/home/notebook-user/unstructured/partition/pdf_image/ocr.py", line 166, in process_file_with_ocr
    merged_page_layout = supplement_page_layout_with_ocr(
  File "/home/notebook-user/unstructured/utils.py", line 214, in wrapper
    return func(*args, **kwargs)
  File "/home/notebook-user/unstructured/partition/pdf_image/ocr.py", line 202, in supplement_page_layout_with_ocr
    ocr_layout = ocr_agent.get_layout_from_image(
  File "/home/notebook-user/unstructured/partition/utils/ocr_models/tesseract_ocr.py", line 48, in get_layout_from_image
    ocr_df: pd.DataFrame = unstructured_pytesseract.image_to_data(
  File "/usr/local/lib/python3.10/site-packages/unstructured_pytesseract/pytesseract.py", line 591, in image_to_data
    return {
  File "/usr/local/lib/python3.10/site-packages/unstructured_pytesseract/pytesseract.py", line 593, in <lambda>
    Output.DATAFRAME: lambda: get_pandas_output(
  File "/usr/local/lib/python3.10/site-packages/unstructured_pytesseract/pytesseract.py", line 568, in get_pandas_output
    return pd.read_csv(BytesIO(run_and_get_output(*args)), **kwargs)
  File "/usr/local/lib/python3.10/site-packages/unstructured_pytesseract/pytesseract.py", line 347, in run_and_get_output
    run_tesseract(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/unstructured_pytesseract/pytesseract.py", line 279, in run_tesseract
    raise TesseractError(proc.returncode, get_errors(error_string))
unstructured_pytesseract.pytesseract.TesseractError: (-8, 'Estimating resolution as 252')
```

**Comment by qued** [comment]
Slack conversation: https://unstructuredw-kbe4326.slack.com/archives/C044N0YV08G/p1713364225537139

We've previously encountered this error in #1920 and closed the issue with #1996. The user is running a version of `unstructured` with the fix merged, so presumably this is the same error showing up for a different reason.

**Comment by esakes1** [comment]
@qued Any update on the above issue ?

**Comment by scanny** [comment]
@esakes1 Can you say more about what you're seeing and when? In particular which specific error message (including estimated resolution).

And can you provide an example document with which we can reproduce?

**Comment by eponraj27392** [comment]
@scanny  & @qued 

Sorry for taking so long time for uploading the documents.  

Kindly find the attached file which cause the below same error

```
unstructured.ingest.error.PartitionError: Error in partitioning content: API error occurred: Status 500
{"detail":"(-8, 'Estimating resolution as 206')"}
```

Stack details 
API version (deployed locally as standalone) - 0.0.75

Unstructured version
unstructured==0.14.6
unstructured-client==0.18.0 
[Tesseract_failure.pdf](https://github.com/user-attachments/files/17676755/Tesseract_failure.pdf)

**Comment by eponraj27392** [comment]
@scanny  & @qued 

Hi,
FYI, We updated the US-API version 0.81.0 but the issue still persists.
Plz let us know how can we proceed further.

**Comment by AhmedAl-Zanam** [comment]
Hi @qued and @scanny
@eponraj27392 and me are wokring on same thing.We're still facing same issue with Tesseract after updating to 0.81.0.
Are you planning to release new version soon (before charismas time)?
cheers

**Comment by vignesht30** [comment]
Facing the same issue. 
Running in ubuntu 22.04 LTS.
installed unstructured using -> pip install "unstructured[all-docs]"==0.16.5
 tesseract --version
tesseract 5.4.0
 leptonica-1.85.0
  libgif 5.1.9 : libjpeg 8d (libjpeg-turbo 2.1.2) : libpng 1.6.37 : libtiff 4.3.0 : zlib 1.2.11 : libwebp 1.2.2 : libopenjp2 2.4.0
 Found AVX512BW
 Found AVX512F
 Found AVX2
 Found AVX
 Found FMA
 Found SSE4.1

I tested the same in my windows laptop, it works fine. 
Appreciate your help. Thanks in advance.

**Comment by mkdev5** [comment]
Hi @qued @badGarnet, I’d like to fix the -8 “Estimating resolution” error by passing an explicit DPI to Tesseract (e.g. user_defined_dpi=300) so it skips resolution estimation, and optionally retrying once on this specific TesseractError. Does that approach work for you, or would you rather handle it another way?
