### ISSUE TITLE
bug/`page_number` still appears in `partition_html` metadata if `include_metadata` is set to `False`

### ISSUE THREAD

**Issue by MthwRobinson** [Unstructured-IO/unstructured#592]
**Describe the bug**
If you use `partition_html` with `include_metadata=False`, `page_number` is still included in the metadata.

**To Reproduce**
```python
from unstructured.partition.html import partition_html

filename = "example-docs/example-10k.html"
elements = partition_html(filename=filename, include_metadata=False
```

**Expected behavior**
`page_number` should not be in the metadata.

**Desktop (please complete the following information):**
 - `unstructured==0.6.6`
 - Python version 3.8

**Comment by Coniferish** [comment]
Hey @MthwRobinson. I'm starting to look into this and want to make sure that you're saying that the `page_number` attribute shouldn't exist at all in the metadata, not just that it should be `None`. I am only seeing `None` values when I run the steps to reproduce, but realize I might be using a more recent version of unstructured and that could be creating the difference.

**Comment by MthwRobinson** [comment]
Hey @Coniferish - yeah the attribute should exist but be None. If all of the attributes are None when include_metadata=False, that’s the correct behavior. Possible this might have been corrected already. If that’s the case I think it would still be worthwhile to add in the code you used to verify as a unit test.

**Comment by Coniferish** [comment]
Sounds good. I can write a test for that

**Comment by Coniferish** [comment]
@MthwRobinson I must have been looking at `page_name` instead of `page_number` because I see the bug you mentioned. I'll look into it and write a test for disabling metadata

**Comment by Coniferish** [comment]
Hey @MthwRobinson 

I've found the issue, but am unsure of the best way to address it.

`partition_html` is decorated by `add_metadata_with_filetype`, which currently just returns the elements as-is if `include_metadata = False`. The page number already exists in the element, so that's why we're still seeing it.

I'm wondering if it'd make sense to create a `_remove_element_metadata` method to call. I'm looking at the `_add_element_metadata` (when `include metadata = True`) and wondering what all needs to be included if I'm creating a new method:
```
 if hasattr(layout_element, "text_as_html"):
            text_as_html: Optional[str] = layout_element.text_as_html
```
One question I have is what this^ block is doing. If it does have `"text_as_html"`, that variable isn't being used anywhere it seems.


Here's the full method:
`unstructured/partition/common.py`:
```
def _add_element_metadata(
    layout_elements,
    include_page_breaks: bool = False,
    filename: Optional[str] = None,
    filetype: Optional[str] = None,
    url: Optional[str] = None,
) -> List[Element]:
    """Adds document metadata to the document element. Document metadata includes information
    like the filename, source url, and page number."""
    elements: List[Element] = []
    page_number: int = 1
    for layout_element in layout_elements:
        element = normalize_layout_element(layout_element)
        if hasattr(layout_element, "text_as_html"):
            text_as_html: Optional[str] = layout_element.text_as_html
        else:
            text_as_html = None
        metadata = ElementMetadata(
            filename=filename,
            filetype=filetype,
            url=url,
            page_number=page_number,
            text_as_html=text_as_html,
        )
        if isinstance(element, list):
            for _element in element:
                _element.metadata = metadata.merge(_element.metadata)
            elements.extend(element)
        elif isinstance(element, PageBreak):
            page_number += 1
            if include_page_breaks:
                elements.append(element)
        else:
            element.metadata = metadata.merge(element.metadata)
            elements.append(element)
    return elements
```

And if I'm going to create `_remove_element_metadata`, is okay to just hard code the metadata values to `None` and omit the `isinstance` checks?

**Comment by MthwRobinson** [comment]
Yeah I think `if hasattr(layout_element, "text_as_html"):` is unnecessary because `text_as_html` is never not an attribute on `ElementMetadata`. If it _is_ necessary and you take it out, I think `mypy` will yell at you when you run `make check`.

If you add `_remove_element_metadata` it would be fine to hardcode the metadata values to `None` without the `isinstance` checks. It may be easier to just set `element.metadata = ElementMetadata()` instead, since that would set all of the metadata values to `None` without any additional code.

**Comment by Coniferish** [comment]
Hey @MthwRobinson 

I want to double-check that _all_ metadata fields should be `None`:
`ElementMetadata(filename=None, file_directory=None, date=None, filetype=None, page_number=None, page_name=None, url=None, sent_from=None, sent_to=None, subject=None, text_as_html=None)`

Also, there is this question on Slack about the page_number attr: https://unstructuredw-kbe4326.slack.com/archives/C044N0YV08G/p1685029750453469

In the `_add_element_metadata` method, it automatically adds `page_number = 1`. Is that the desired behavior? I see that the page number is incremented later in the method and that slack question is about `parition_pdf` instead of `partition_html`, but wanted to ask about it since I'm already in this part of the code.

**Comment by bcartier** [comment]
In that thread on Slack both Akshat and I encountered the page number issue using **partition_pdf**. In case it helps, here's the PDF and and the JSON result with all page numbers coming back as "1":

[sample.pdf](https://github.com/Unstructured-IO/unstructured/files/11582941/sample.pdf)
[sample.json.txt](https://github.com/Unstructured-IO/unstructured/files/11582946/sample.json.txt)

**Comment by MthwRobinson** [comment]
@bcartier - Thanks for the example file, we've opened #650 for the page number issue and will pick it up as soon as we can.

**Comment by MthwRobinson** [comment]
> Hey @MthwRobinson
> 
> I want to double-check that _all_ metadata fields should be `None`: `ElementMetadata(filename=None, file_directory=None, date=None, filetype=None, page_number=None, page_name=None, url=None, sent_from=None, sent_to=None, subject=None, text_as_html=None)`
> 
> Also, there is this question on Slack about the page_number attr: https://unstructuredw-kbe4326.slack.com/archives/C044N0YV08G/p1685029750453469
> 
> In the `_add_element_metadata` method, it automatically adds `page_number = 1`. Is that the desired behavior? I see that the page number is incremented later in the method and that slack question is about `parition_pdf` instead of `partition_html`, but wanted to ask about it since I'm already in this part of the code.

@Coniferish - Yeah, all of the elements should be `None` if `include_metadata=False`. That's `include_metadata=False` is generally used if you want to limit the size of the payload or if you're using `partition_html` as part of another partitioning function. The PDF issue is separate, in that case it looks like `page_number` doesn't increment beyond page 1.

**Comment by MthwRobinson** [comment]
Fixed in #658
